# Generated by Django 3.0.8 on 2020-07-29 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartesianPlans',
            fields=[
                ('id_cartesian_plan', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('axis_x', models.IntegerField()),
                ('axis_y', models.IntegerField()),
            ],
            options={
                'db_table': 'cartesian_plans',
                'managed': True,
            },
        ),
    ]
