# Generated by Django 3.0.8 on 2020-07-30 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('probes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probes',
            name='direction',
            field=models.CharField(choices=[('N', 'N'), ('S', 'S'), ('W', 'W'), ('E', 'E')], max_length=1),
        ),
    ]
