# Generated by Django 3.0.8 on 2020-07-30 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('probes', '0002_auto_20200730_0005'),
        ('instructions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructions',
            old_name='instruct',
            new_name='instruction',
        ),
        migrations.AlterField(
            model_name='instructions',
            name='id_probe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='probes.Probes'),
        ),
    ]
